gsap.from('.logo', {opacity:0, duration:1, delay:2, y:10})
gsap.from('.image', {opacity:0, duration:1, delay:2.1, y:30, stagger:0.2})
gsap.from('.title', {opacity:0, duration:1, delay:1.6, y:30})
gsap.from('.description', {opacity:0, duration:1, delay:1.8, y:30})
gsap.from('.hashtags', {opacity:0, duration:1, delay:1.8, y:30})
gsap.from('.buttons', {opacity:0, duration:1, delay:2.1, y:30})
gsap.from('.social', {opacity:0, duration:1, delay:2.3, y:30})
